version: "3"

services:
  simple-issue-tracker:
    build: .
    image: simple-issue-tracker:latest
    depends_on:
      - docker-mysql
    ports:
      - 8765:8765
    restart: always
    networks:
      - app_net
  docker-mysql:
    container_name: mysql-db
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    networks:
      - app_net
networks:
  app_net:
    driver: "bridge"
