server:
  port: 8765

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issuetrackerdb?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: changeit
    initialization-mode: always
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  #    jackson:
  #        date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
logging:
  level.org.hibernate.type.descriptor.sql: trace
  level.org.springframework.web: trace
